### ISSUE TITLE
A lot of the creature names are backwards.

### ISSUE THREAD

**Issue by CharonM72** [Kromtec/Legends-Viewer#15]
"Loz Bitejaw the Attack of Burning
Is a **colossus bronze** born in -189."

" In 41, midsummer, (Malachite, 15) the human werebeast Pirni Steamsnack devoured a male **bird chicken** in Waxbrain. In The 2nd rampage of Pirni Steamsnack."

"5 **Bear Grizzly** Men"

I think this is a pretty ubiquitous problem.

**Comment by Kromtec** [comment]
Can you confirm whether this issue still happens when exporting the xmls with the enhanced [exportlegends script](https://raw.githubusercontent.com/robertjanetzko/dfhack/additional-exports/scripts/exportlegends.lua)?

**Comment by CharonM72** [comment]
When loading the legends_plus xml exported with the enhanced exportlegends script, LV crashes.

**Comment by CharonM72** [comment]
Note: it does not crash when the legends_plus is not loaded. In this case, it shows the animal names correctly.

**Comment by Kromtec** [comment]
I just released 1.16.01. This should get rid of the crashes with the enhanced exportscript. 
If it keeps crashing please upload the save to DFFD.

**Comment by CharonM72** [comment]
Crash fixed, and the bug also appears to be fixed.
