### ISSUE TITLE
Crash in charts

### ISSUE THREAD

**Issue by Algorithman** [Kromtec/Legends-Viewer#25]
If you select a chart of a fort (with quite something going on) and then switch to World->Historical Figures Remaining, it crashes if there are some historical figures of UNKNOWN race.

ChartPanel.cs line 495:
var hfKilled = World.Events.OfType<HFDied>().GroupBy(death => death.HistoricalFigure.Race).Select(hf => new { Race = hf.Key, Count = hf.Count() }).OrderBy(hf => **hfTotals.IndexOf(hfTotals.First(hf1 => hf1.Race == hf.Race))**).ToList();

**Comment by Kromtec** [comment]
Thanks, to order this list wasn't even necessary in the first place.
