### ISSUE TITLE
Cannot select xml file 

### ISSUE THREAD

**Issue by megaBadger** [Kromtec/Legends-Viewer#26]
I cannot currently select the xml file to load within LV 1.17.01 as the ellipses button ('...') does not show up next to any of the items in the Summary tab. [This](https://imgur.com/GrjJhdz) image show an example of what I'm talking about. 

I have read through the readme and troubleshooting tips but can't seem to figure this out. My IE is version 11 so I don't think that's the problem. Also I tried using version 1.13 and the button shows up.

**Comment by Kromtec** [comment]
I have never heard of this bug and can not reproduce it myself. Maybe it is DPI related? Do you have a high resolution monitor?

**Comment by megaBadger** [comment]
Hmm I am using a 1440p monitor as my main display, but my peripheral monitors are 1080p and the button doesn't show up on them either. I'll give it another shot though. Super weird...

**Comment by Kromtec** [comment]
Please reopen if your problem is still there in v1.18.00+

**Comment by Kromtec** [comment]
It looks like Windows Forms does not do well with custom scaling. 125% 150% 225% were fine but with 113% scaling factor I could reproduce this bug.  I changed the order of the controls so that the buttons are on the left side of the textboxes and made a few other tweaks.
