### ISSUE TITLE
Issue with viewing civilizations.

### ISSUE THREAD

**Issue by Simcrafter** [Kromtec/Legends-Viewer#38]
When attempting to view a civilization I get an Unhandled Exception, "Object Reference not set to an instance of an object." What does this mean/ Is it an error in my data exports or an issue with the software?

**Comment by Kromtec** [comment]
Have you tried with Legends Viewer 1.19.08? I fixed a bug in 1.19.08 that could exactly be your issue.

**Comment by Simcrafter** [comment]
I'm using version 1.19.08 just as a note with some further testing it only seemed to happen with some civilizations, I also had it happen with a site at one point. I have yet to try it with other worlds so it could have been a generation issue. (Note: Definitely not an export issue I re-exported all the files using DF-Hack and it made no difference.)

**Comment by Kromtec** [comment]
Can you upload a zip that contains these files:
_regionx-xxxxx-xx-xx-legends.xml
regionx-xxxxx-xx-xx-legends_plus.xml
regionx-xxxxx-xx-xx-world_history.txt
regionx-xxxxx-xx-xx-world_map.bmp
regionx-xxxxx-xx-xx-world_sites_and_pops.txt_

And post the name of the civilizations and site if you can remember.

**Comment by Simcrafter** [comment]
Sorry for the long response time I got stuck without a computer for a while.
The civilization was called The Fondled Ships.
I can't remember the site.
Here is a link to the zip (too big to upload).
https://drive.google.com/open?id=1iG5Gbxh8KL9Ch_cGcvII-V1SqnZw6QbB

**Comment by Kromtec** [comment]
It looks like your exported files are corrupt. Some of the events are missing information that is normally always set.
Which version of Dwarf Fortress and DFHack did you use? 

Nonetheless, I will  make my code more robust so that LegendsViewer will not crash if these types of data are not there.

**Comment by Kromtec** [comment]
fixed in v1.19.09
