### ISSUE TITLE
Minor grammar issues

### ISSUE THREAD

**Issue by CharonM72** [Kromtec/Legends-Viewer#7]
"In 147, midsummer, (Galena, 1)  The Misty Wisps attacked  The Crimson Confederation in The Distracting Dunes. the elf Fecici Yawnsmiles led the attack, and the defenders were led by the human Ite Waxyplot. In The Furious Battles as part of The Fierce Conflict."

Galena, 1 should be changed to Galena 1 or 1st of Galena
The second comma should be after (Galena, 1)
"the" should be capitalized
The last two sentences should be merged into one sentence

**Comment by Kromtec** [comment]
The "In The Furious Battles as part of The Fierce Conflict." part of the event text is additional info that describes the event collection which contains this event. Its the same issue as #10 with the "In a journey." text.

I fixed the date and restructured the text. Until I find a better solution for event collection infos I will leave #10 open.
